version: '3'
services:
  app:
    build:
      context: .
    image: jasimatiyeh/web
    environment:
      - FLASK_ENV=development
    ports:
      - 5000:5000
  redis:
    image: redis:4.0.11-alpine